apiVersion: skaffold/v4beta11
kind: Config
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: open-match-director
      context: .
      docker:
        dockerfile: ./cmd/director/Dockerfile
    - image: open-match-gamefront
      context: .
      docker:
        dockerfile: ./cmd/gamefront/Dockerfile
    - image: open-match-matchfunction
      context: .
      docker:
        dockerfile: ./cmd/mmf/Dockerfile
deploy:
  kubectl:
    defaultNamespace: open-match
manifests:
  rawYaml:
    - ./cmd/director/director.yaml
    - ./cmd/gamefront/gamefront.yaml
    - ./cmd/mmf/mmf.yaml
portForward:
  - resourceType: Service
    resourceName: open-match-frontend
    namespace: open-match
    port: 50504
    localPort: 50504
  - resourceType: Service
    resourceName: open-match-backend
    namespace: open-match
    port: 50505
    localPort: 50505
